sudo: required
services:
        - docker

before_install:
        - docker build -t dpuri0905/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true dpuri0905/react-test npm test

after_success:
        - docker build -t dpuri0905/multi-client ./client
        - docker build -t dpuri0905/multi-nginx ./nginx
        - docker build -t dpuri0905/multi-server ./server
        - docker build -t dpuri0905/multi-worker ./worker
          #log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          #Take those images to docker hub
        - docker push dpuri0905/multi-client
        - docker push dpuri0905/multi-nginx
        - docker push dpuri0905/multi-server
        - docker push dpuri0905/multi-worker
